services:
  backend:
    build: ./back-end
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://mustafa:admin@db:5432/link-shortner?schema=public
      JWT_SECRET: '123'
    depends_on:
      - db

  frontend:
    build: ./front-end
    ports:
      - "3006:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mustafa
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: link-shortner
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
